version: '3'

services:
  solr:
    image: solr:9.4.0
    ports:
      - "8983:8983"
    volumes:
      - ./solr_data:/var/solr
    environment:
      - SOLR_HEAP=2g
    command:
      - solr-precreate
      - articles
